### ISSUE TITLE
NameError: name 'RandomSampler' is undefined

### ISSUE THREAD

**Issue by Sujz13** [yueliu1999/ELCRec#5]
When running main.py, I ran into the following problem, can the author please answer it?
“Traceback (most recent call last):
  File “/home/sjz/RS/ELCRec-main/src/main.py”, line 234, in <module
    main()
  File “/home/sjz/RS/ELCRec-main/src/main.py”, line 169, in main
    train_sampler = RandomSampler(train_dataset)
NameError: name 'RandomSampler' is undefined”

**Comment by yueliu1999** [comment]
from torch.utils.data import DataLoader, SequentialSampler, RandomSampler

we update the code.

**Comment by yueliu1999** [comment]
we clear up and update the code, please check the latest code.
